### ISSUE TITLE
Add a Makefile

### ISSUE THREAD

**Issue by jvehent** [mozilla/masche#18]
The project should have a Makefile at the root that can build the various examples and run the tests.

**Comment by alcuadrado** [comment]
@mvanotti The aside that you mention is already implemented. It makes sense for me. Which is the state of this on Windows? 

@jvehent currently on OS X and Linux you can run make on the root of the project and everything gets tested. The go modules can be built with the standar `go build` command.

**Comment by jvehent** [comment]
:+1: very cool!

**Comment by alcuadrado** [comment]
Marco, can you make sure this works on windows? Also, check if the OS is 32 bits, and in that case don't run 64 bits tests.
