### ISSUE TITLE
Permission Denied is being reported as a softerror instead of harderror

### ISSUE THREAD

**Issue by mvanotti** [mozilla/masche#20]
memaccess reports a permission denied as a softerror instead of a harderror

This is the softerror:

"Retries exceeded on reading 2048 bytes starting at 8048000: Error while reading 2048 bytes starting at 8048000: open /proc/22470/mem: permission denied"

Also, the error description is very redundant. Should we do something about it?

**Comment by alcuadrado** [comment]
@mvanotti Could you please explain how to reproduce this bug?

**Comment by mvanotti** [comment]
Run the application without sudo from Linux
