### ISSUE TITLE
Global Makefile shouldn't run 64-bits tests

### ISSUE THREAD

**Issue by jvehent** [mozilla/masche#25]
Running on Fedora 21, with glibc-headers x86_64 and i686 installed, I get the following:

```
$ make all
go get -u github.com/mozilla/masche/process
go get -u github.com/mozilla/masche/memsearch
go get -u github.com/mozilla/masche/memaccess
go get -u github.com/mozilla/masche/listlibs
make -C test/tools test64
make[1]: Entering directory '/home/ulfr/git/masche/test/tools'
gcc -Wall -Wextra -pedantic -std=c99 -O0 known_byte_sequences.c -o test
make[1]: Leaving directory '/home/ulfr/git/masche/test/tools'
go test ./memaccess ./memsearch ./process
ok  	_/home/ulfr/git/masche/memaccess	0.139s
ok  	_/home/ulfr/git/masche/memsearch	0.076s
ok  	_/home/ulfr/git/masche/process	0.024s
make -C test/tools test32
make[1]: Entering directory '/home/ulfr/git/masche/test/tools'
gcc -Wall -Wextra -pedantic -std=c99 -O0 known_byte_sequences.c -m32 -o test
In file included from /usr/include/features.h:389:0,
                 from /usr/include/stdlib.h:24,
                 from known_byte_sequences.c:2:
/usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
                           ^
compilation terminated.
Makefile:11: recipe for target 'test32' failed
make[1]: *** [test32] Error 1
make[1]: Leaving directory '/home/ulfr/git/masche/test/tools'
Makefile:22: recipe for target 'testbin32' failed
make: *** [testbin32] Error 2
```

**Comment by alcuadrado** [comment]
Thanks for reporting this Julien! We need to update the gloabl Makefile so it doesn't run 64-bits tests on 32-bits OS's.

**Comment by jvehent** [comment]
You mean the opposite: not run 32 tests on 64 bits machines?

**Comment by alcuadrado** [comment]
There are two things being built there: masche's code and a small program to use as test case.

Masche's code is always compiled in the natural mode of the platform.

The test case program is now compiled (and run) in 32 *and* 64 bits modes.  This makes sense in a 64 bit platform: you test 64-bits-masche with 32 & 64 bits processes. But in a 32 bits platform (WIN32 and Linux 32 bits for us) running a 64 bit test case program is not possible, so we should detect these platforms and don't try to do it.

**Comment by jvehent** [comment]
What  you say makes perfect sense, but I don't think it addresses the issue: I'm on a 64 bits platform trying to build the test file in 32 bits, and it fails.

```bash
$ gcc -Wall -Wextra -pedantic -std=c99 -O0 known_byte_sequences.c -m32 -o test32
In file included from /usr/include/features.h:389:0,
                 from /usr/include/stdlib.h:24,
                 from known_byte_sequences.c:2:
/usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
                           ^
compilation terminated.
```

**Comment by alcuadrado** [comment]
That's weird, I don't have much experience with Fedora, but I guess you
missing some package necessary for building 32 bit apps in 64 bit systems.
The error comes from stdlib.h, so 32 bits glibc maybe?

**Comment by jvehent** [comment]
Ha, you're correct, I had glibc-headers for i686, but I was missing glibc-devel i686. All the tests pass now.
