### ISSUE TITLE
go: Command not found

### ISSUE THREAD

**Issue by pavlinux** [mozilla/masche#26]
# make 
go get -u github.com/mozilla/masche/process
make: go: Command not found
Makefile:7: recipe for target 'get' failed
make: *** [get] Error 127

What is go?
Where is in Readme? 
Go must die, Rewrite on C++ :-P

**Comment by jvehent** [comment]
Go is a new programming language. You probably haven't heard of it. Although, you do no about C++ which indicates that you're aware of what a programming language is. Anyway, Go can be installed on your system using something called a "package manager", or it's graphical equivalent often called "software something something".

Try installing Go, and it should solve all your compilation problems ever. I hear it makes people happier too, but there's no scientific study on that yet.
