### ISSUE TITLE
Add `offset` and `maxlength` options to WalkMemory

### ISSUE THREAD

**Issue by jvehent** [mozilla/masche#29]
WalkMemory currently supports starting at a given address. It would be nice to also support stopping after X number of bytes are read. This should be exported in `memsearch` as well.
I'd also suggest renaming the starting point `address` into `offset` to match terms commonly used for this purpose.

**Comment by mvanotti** [comment]
Could you provide a compelling use case for this functionallity?

I think you can achieve this without modifying WalkMemory: WalkMemory receives a function as a parameter that let's it know when to stop searching. You can use a closure that counts the amount of bytes read and stop after N bytes.

So, it looks like the functionality should be bundled with the function passed to WalkMemory. You can provide your example function and if it is practical we can add it to the library :)

**Comment by jvehent** [comment]
Thanks Marco, I'll give it a shot in the function passed to WalkedMemory first, and reopen this if necessary.

Maybe we should add a basic walker template to path to walkmemory to help people use the library? Or maybe add one to the doc?

**Comment by mvanotti** [comment]
I think the basic templates can be found on memsearch module (using grep and linear search), but maybe we can add an example in the doc.
