### ISSUE TITLE
Fix stylistic issues

### ISSUE THREAD

**Issue by jvehent** [mozilla/masche#32]
Go Report Card has a thing or two to say about the code. It would be nice to address them: https://goreportcard.com/report/github.com/mozilla/masche

**Comment by vbmade2000** [comment]
@jvehent I would like to work on this if you don't mind.

**Comment by jvehent** [comment]
Go for it!

**Comment by vbmade2000** [comment]
@jvehent I think We can close this. It was addressed in #36
